#!/bin/bash
#SBATCH --job-name=FE6_2048
#SBATCH --time=48:00:00
#SBATCH -p aaiken
#SBATCH --gres gpu:1
#SBATCH --nodes=1

source ${HOME}/setup.bash
cd ${HOME}/SLAC_FEL_data/training

NUM_HIDDEN_LAYERS=6
NUM_HIDDEN_UNITS_PER_LAYER=2048
LEARNING_RATE=0.0001
EPOCHS=250000
INITIAL_EPOCH=0
OPTIMIZER=Adam
DIRECTION=forward
ROOT=$SCRATCH/checkpoint/${DIRECTION}_${OPTIMIZER}_${NUM_HIDDEN_LAYERS}_${NUM_HIDDEN_UNITS_PER_LAYER}

python train_keras.py ${NUM_HIDDEN_LAYERS} ${NUM_HIDDEN_UNITS_PER_LAYER} ${LEARNING_RATE} ${EPOCHS} ${INITIAL_EPOCH} ${OPTIMIZER} ${DIRECTION} ${ROOT}


